#!/user/bin/env python3

# create wordbank
wordbank= ["indectation", "spaces"]

# create tlg students list
tlgstudents= ['Albert', 'Anthony', 'Brenden', 'Craig', 'Deja', 'Elihu', 'Eric', 'Giovanni', 'James', 'Joshua', 'Maria', 'Mohamed', 'PJ', 'Philip', 'Sagan', 'Suchit', 'Meka', 'Trey', 'Winton', 'Xiuxiang', 'Yaping']

# create integer
workbank.append(4)

# create number between 0-20
num= input("Pick a student number!")

# create a integer from a string
num= int(input("Pick a student number!"))

# create a slice from the tlgstudents
choice= int(input("Pick a student number!"))
student_name= tlgstudents[choice]

# create tlgstudnets lis and student_name string
print("student_name", always uses [4] "spaces" to indent:)


